### ISSUE TITLE
数据库连接

### ISSUE THREAD

**Issue by hunanhd** [anheihb03dlj/cbm#2]
如果客户机上未安装MySQL，在启动提示数据库连接失败，这种情况输入命令会假死。
修改建议：在连接失败的情况下不加载arx，或者直接退出CAD。

**Comment by anheihb03dlj** [comment]
已解决，双保险检查数据库连接!
（1）在launcher项目的CLauncherApp::InitInstance中检查数据库是否连接正常
（2）在ArxSOUI项目的CArxSoUIApp::On_kInitAppMsg中也检查数据库是否正常
